name: cs472
channels:
  - defaults
dependencies:
  - matplotlib=3.0.3
  - numpy=1.16.3
  - numpy-base=1.16.3
  - pandas=0.24.2
  - python=3.6.8
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - pip=19.1.1
  - pip:
    - liac-arff==2.3.1